### ISSUE TITLE
Add support for Angular or a sample that works calling into an Angular app function

### ISSUE THREAD

**Issue by jimbarrett33** [OfficeDev/Office-Add-in-Commands-Samples#13]
Commands are great and I'm using them in my Add-Ins but I can't figure a way to call "into" an Angular app via the function file or have the Angular app be the function file. So all I can do is use one command icon on the ribbon that just launches the app.  This is OK but I have several places in my add-in where it makes sense to invoke an action that could be map to either a ribbon button or the context menu that works integrates with the state I have running in the add-in.

If you have any examples or plan some support in the future that would be great.  (BTW, the same is true of the Dialog API -- it has to call a URL on the server and there is no way to pass info to it from an Angular app already on the client unless I post back with all the data I want the dialog to show).

More details of what I have tried...
- if I point the URL of the function file to my main angular entry page "app.html" (or .aspx) it won't work;  I tried adding a unique URL param to try and get the entire add-in to reload in the Task Pane with a diffn context and load the angular app with a different function entry point but the call does not reload the add-in like Outlook Add-in's do.  Having to reload the entire add-in is not ideal anyway as I just want to call a method on some angular service/object.
- if I create a separate function file (i.e. not app.html) with the same angular app code it doesn't work either since this is a different instance of the angular app (and a diffn DOM) and can't interact with the app.html angular app

**Comment by LezaMax** [comment]
@Rick-Kirkham  will you follow up or reassign? I believe we might already have an Angular sample that uses commands but not sure

**Comment by jimbarrett33** [comment]
An Angular example for both Dialog API and functions would be great. I have an Excel add-in that I want to provide a wizard experience using the larger dialog surface and pass the resulting data back to my already running Angular app. Thanks.

**Comment by ndeeH** [comment]
@LezaMax Where is the angular sample?

**Comment by Rick-Kirkham** [comment]
@weird-dreams 
We don't have a sample of an Angular-based add-in that uses add-in commands. This is an inherently difficult scenario since Angular add-ins are single page apps, but the Function Files of add-in commands, and the Dialog, are all separate pages from the task pane. The only way to communicate between the app running in the task pane and the function files or dialog is through Local Storage. One side of the conversation stores a message in a Local Storage entry. The other side has to have a loop and a timer designed so that it periodically checks that entry for messages. (The exception to this is messages from the dialog to the parent task pane or function file. For those, the dialog can use the messageParent API.)
